- name: 古いmysqlリポジトリを削除
  yum: name=mysql* state=removed

- name: postgresql用rpm インストール
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    state: present

- name: postgresqlインストール
  yum: name={{item}} state=latest
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-devel
    - postgresql96-contrib
    - python-psycopg2

- name: ポート解放
  lineinfile:
    dest: /etc/sysconfig/iptables
    state: present
    insertafter: -A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
    line:  -A INPUT -m state --state NEW -m tcp -p tcp --dport {{ item }} -j ACCEPT
  with_items:
    - 3306

- name: ファイアウォール設定
  service: name=iptables enabled=yes state=restarted

- name: DB初期化
  shell: service postgresql-9.6 initdb

- name: pg_hba.confバックアップ
  shell: cp /var/lib/pgsql/9.6/data/pg_hba.conf /var/lib/pgsql/9.6/data/pg_hba.conf.default

- name: postgresql.confバックアップ
  shell: cp /var/lib/pgsql/9.6/data/postgresql.conf /var/lib/pgsql/9.6/data/postgresql.conf.default

- name: pg_hba.confファイル更新
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf

- name: postgresql.confファイル更新
  template:
    src: postgresql.conf
    dest: /var/lib/pgsql/9.6/data/postgresql.conf

- name: postgresql起動
  service: name=postgresql-9.6 state=restarted enabled=yes

- name: DB作成
  postgresql_db:
    name: "{{ database.name }}"
    login_user: postgres
    encoding: UTF-8
    state: present

- name: ログインユーザー設定
  postgresql_user:
    name: "{{ database.user }}"
    password: "{{ database.pass }}"
    state: present
    priv: ALL
    db: "{{ database.name }}"
    login_user: postgres
