- name: yumリポジトリ追加
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release

- name: 開発ツールインストール
  yum: name={{item}} state=latest
  with_items:
    - git
    - vim
    - man
    - wget
    - libselinux-python
